# Generated by Django 3.2.2 on 2021-05-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finalapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='student_course_xref',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseID', models.IntegerField()),
                ('studentId', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='GPA',
            field=models.CharField(max_length=500),
        ),
    ]
