# Generated by Django 3.2.2 on 2021-05-09 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Finalapp', '0002_auto_20210509_1349'),
    ]

    operations = [
        migrations.CreateModel(
            name='studentenrollments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=500)),
                ('course', models.CharField(max_length=500)),
            ],
        ),
    ]
